services:
  db:
    image: mysql:8.0
    container_name: booklink-db
    environment:
      MYSQL_DATABASE: booklink
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: booklink-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data:
